#!/bin/sh

estado=`ps aux | grep apache2 | wc -l`
rebootapache=`/etc/init.d/apache2 restart`
correoroot=`echo "Servidor Apache" | mail -s "El servidor Apache estaba parado y se ha Reiniciado" manueljesusbeginesgonzalez@gmail.com`

if [ $estado -le 1 ]; then
  echo "El servidor Apache no esta corriendo"
	echo "A continuacion se procedera a arrancarlo"
	$rebootapache
	$correoroot
	exit 0
else
	echo "El servidro Apache esta corriendo"
	echo "Todo esta OK!"
fi
