#!/bin/sh

estado=`ps aux | grep apache2 | wc -l`
rebootapache=`/etc/init.d/apache2 start`
correoroot=`echo "Servidor Apache" | mail -s "El servidor Apache estaba parado y se ha Reiniciado" manueljesusbeginesgonzalez@gmail.com`
#Si quisieramos mandar a mas de un destinatario, tendriamos que poner "-c" delante de cada correo que queramos añadir de más

while true; do
	if [ $estado -le 1 ]; then
		echo "El servidor Apache no esta corriendo"
		echo "A continuacion se procedera a arrancarlo"
		$rebootapache
		echo "Se ha arrancado Apache"
		$correoroot
		estado=`ps aux | grep apache2 | wc -l`
	else
		echo "El servidro Apache esta corriendo"
		echo "Todo esta OK!"
		estado=`ps aux | grep apache2 | wc -l`
	fi
done
